apiVersion: guardit.gappy.hu/v1
kind: Policy
metadata:
  name: homelab
spec:
  replicaLimit: 5
  allowedRegistries:
    - ghcr.io/gappylul
    - docker.io/library
  requiredLabels:
    - app
  requireResourceLimits: false